-- ==========================================================
-- SUPABASE SCHEMA FOR HYPERVISION WORKSHOP REGISTRATION
-- Execute this script in your Supabase Dashboard -> SQL Editor
-- ==========================================================

-- 1. Table: workshop_registration
CREATE TABLE IF NOT EXISTS public.workshop_registration (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    sap TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL UNIQUE,
    phone TEXT NOT NULL UNIQUE,
    orbit TEXT NOT NULL,
    expectations TEXT NOT NULL,
    attended BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Table: attendance
CREATE TABLE IF NOT EXISTS public.attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sap_id TEXT NOT NULL UNIQUE,
    scanned_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Table: workshop_feedback
CREATE TABLE IF NOT EXISTS public.workshop_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    sap TEXT,
    ratings JSONB NOT NULL,
    avg_rating NUMERIC(4, 2),
    feedback TEXT,
    submitted_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for lightning fast lookups
CREATE INDEX IF NOT EXISTS idx_workshop_reg_sap ON public.workshop_registration(sap);
CREATE INDEX IF NOT EXISTS idx_workshop_reg_email ON public.workshop_registration(email);
CREATE INDEX IF NOT EXISTS idx_workshop_reg_phone ON public.workshop_registration(phone);
CREATE INDEX IF NOT EXISTS idx_attendance_sap ON public.attendance(sap_id);

-- Enable Row Level Security (RLS)
ALTER TABLE public.workshop_registration ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.workshop_feedback ENABLE ROW LEVEL SECURITY;

-- Allow insert/select for public (anon & authenticated roles)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'workshop_registration' AND policyname = 'Allow public registration'
    ) THEN
        CREATE POLICY "Allow public registration" ON public.workshop_registration
            FOR ALL USING (true) WITH CHECK (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'attendance' AND policyname = 'Allow public attendance'
    ) THEN
        CREATE POLICY "Allow public attendance" ON public.attendance
            FOR ALL USING (true) WITH CHECK (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'workshop_feedback' AND policyname = 'Allow public feedback'
    ) THEN
        CREATE POLICY "Allow public feedback" ON public.workshop_feedback
            FOR ALL USING (true) WITH CHECK (true);
    END IF;
END $$;
